intel/graph-compiler

.github/workflows/build-llvm.yml
.gitignore

A bit hacky, but lits are not a part of the llvm installation in any way. We could tar the build itself, but it's larger. Thoughts?

Copy llvm-lit to the llvm installation

---

src/CMakeLists.txt

Add calls to `llvm_update_compile_flags` and `mlir_check_all_link_libraries` for `gc-opt`, as MLIR upstream does for mlir's own executable targets.

build: add llvm_update_compile_flags and mlir_check_all_link_libraries

---

include/gc-dialects/CMakeLists.txt
include/gc-dialects/Passes.h
include/gc-dialects/Passes.td
lib/gc-dialects/CMakeLists.txt
lib/gc-dialects/Transforms/CMakeLists.txt
lib/gc-dialects/Transforms/TileNamed.cpp
scripts/compile.sh
src/CMakeLists.txt
src/gc-opt.cpp
test/CMakeLists.txt
test/gc-dialects/Linlagx/linalg-generalize.mlir
test/lit.cfg.py
test/lit.site.cfg.py.in

This commit enables LIT tests and introduces example of MLP LIT test.
To run all of them use:
```sh
cmake --build . --target gc-check
```
Also introduced infrastructure for adding Passes and registered dummy TileNamedLinalg pass.
Currently it simply print matmuls. To enable use option: "--tile-named-linalg".
Signed-off-by: Dmitrii Makarenko <dmitrii.makarenko@intel.com>

[Testing and Infra] LIT testing and passes enabling

---

.github/dockerfiles/env/Dockerfile
.github/dockerfiles/runner/Dockerfile
.github/dockerfiles/runner/build.sh
.github/workflows/build-llvm.yml
.github/workflows/build.yml
cmake/onednn.cmake
scripts/compile.sh

Add lit tests

---

CMakeLists.txt
cmake/version.cmake
include/gc_version.h
src/dnnl/dnnl_graph_compiler.cpp
test/dnnl/test_dnnl_c_interface.cpp

Align with the GC API changes made in https://github.com/kurapov-peter/oneDNN/pull/1 (implemented a getter function for GC version `dnnl_graph_compiler_get_version`)

Implement a version getter for the graph compiler

---

.github/dockerfiles/env/Dockerfile

Fix env dockerfile

---

include/gc/Transforms/Passes.td
lib/gc/Transforms/CMakeLists.txt
lib/gc/Transforms/OneDNNGraphToLinalg.cpp
test/gc/Dialect/OneDNNGraph/onednn-graph-to-linalg.mlir

Same as [PR #61](https://github.com/intel/graph-compiler/pull/61), which is merged but was not based of main. Should be based of main then merge, thus cherry-pick to this PR from the original merged code to run CI and prepare to merge to main.

[Transform] Add basic onednn_graph dialect lowering

---

.github/workflows/license.yml
include/gc_version.h
lib/gc/Dialect/Linalgx/LinalgxDialect.cpp
lib/gc/Dialect/Linalgx/LinalgxOps.cpp
lib/gc/Dialect/Microkernel/MicrokernelDialect.cpp
lib/gc/Dialect/Microkernel/MicrokernelOps.cpp
lib/gc/Dialect/OneDNNGraph/OneDNNGraphDialect.cpp
lib/gc/Dialect/OneDNNGraph/OneDNNGraphOps.cpp
lib/gc/Transforms/OneDNNGraphToLinalg.cpp
lib/gc/Transforms/TileNamed.cpp
scripts/license.py
test/dnnl/dnnl_test_utils.hpp
test/dnnl/test_dnnl_c_interface.cpp
unittests/Example/Example.cpp

Add license check
Files in the changeset with suffix `.c`, `.cpp`, `.h`, `.hpp`, `.py`, `CMakeLists.txt` will be checked.
Please see the result at #86 and [url](https://github.com/intel/graph-compiler/actions/runs/9124527004/job/25088869295?pr=86)

action: add license check

---

include/gc/Dialect/OneDNNGraph/OneDNNGraphOps.h
include/gc/Dialect/OneDNNGraph/OneDNNGraphOps.td
include/gc/Dialect/OneDNNGraph/OneDNNGraphTypes.td
lib/gc/Dialect/OneDNNGraph/OneDNNGraphOps.cpp

Some small changes：
1. Use broadcast trait to replace some functions.
2. Add some data types.

[OneDNN Graph Dialect] Use Broadcast Trait and organize data types

---

.gitignore
scripts/compile.sh

In some cases, when using different versions of the compiler/libc to build the llvm-project and other parts of the project, linking errors occur. To avoid this, a new compilation script has been added that will build the llvm project in the specified environment.
Also external projects will be saved in the externals folder so that the user can delete the build directory separately from the external projects.

[Build script] Add compilation script

---

scripts/compile.sh

Remove debug messages. There are still possible misuse of script as options without "-" in the start will be ignored.

[Build script] Fix debug messages

---

scripts/license.py

Try to fix https://github.com/intel/graph-compiler/actions/runs/9205162763/job/25320259726

Remove trailing space in the recommanded license to pass the clang-format check

---

lib/gc/Transforms/CMakeLists.txt

This is a minimal fix for the build issue. We should make it work with dynamic linking and find a better way of populating the library lists.

Fix merge issue with mlir libs linking

---

.github/workflows/coverity.yml

Initial Coverity workflow.
This also requires adding the COVERITY_TOKEN secret.

Add initial coverity workflow

---

src/dnnl/JsonParser.cpp
test/dnnl/TestJsonParser.cpp
test/dnnl/resources/add_relu.json

FIX-#111: oneDnn JsonParser: Convert auto_broadcast attribute to boolean

---

lib/gc/Transforms/Pipeline.cpp

Upstream remove the legacy passes https://github.com/llvm/llvm-project/pull/93535/files
We need to switch to one-shot-bufferization solution now.

Remove use of legacy bufferization passes

---

.github/dockerfiles/env/entrypoint.sh

Add missed file

---

scripts/full_check.sh
scripts/license.py

scripts: support local check for developers

---

CMakeLists.txt
src/dnnl/JsonParser.cpp
src/dnnl/JsonParser.h
src/dnnl/dnnl_graph_compiler.cpp
test/CMakeLists.txt
test/dnnl/CMakeLists.txt
test/dnnl/DnnlTestUtils.h
test/dnnl/TestApiBasic.cpp
test/dnnl/TestJsonParser.cpp
test/dnnl/resources/add.json
test/dnnl/resources/add_relu.json

Depends on https://github.com/intel/graph-compiler/pull/97

FEAT-#128: oneDNN: Implement compilation and execution

---

lib/gc/Transforms/Pipeline.cpp

[Transform][BUG] fix gc-check fail on creating arith pass

---

include/gc/Transforms/Passes.h
include/gc/Transforms/Passes.td
include/gc/Transforms/Utils/MatcherUtils.h
include/gc/Transforms/Utils/StructuredOpMatcher.h
include/gc/Transforms/Utils/ValueUtils.h
lib/gc/CAPI/CMakeLists.txt
lib/gc/ExecutionEngine/Driver/CMakeLists.txt
lib/gc/Transforms/CMakeLists.txt
lib/gc/Transforms/GPU/CMakeLists.txt
lib/gc/Transforms/GPU/LinalgToXeGPU.cpp
lib/gc/Transforms/Utils/CMakeLists.txt
lib/gc/Transforms/Utils/MatcherUtils.cpp
lib/gc/Transforms/Utils/StructuredOpMatcher.cpp
lib/gc/Transforms/Utils/ValueUtils.cpp
src/gc-opt/CMakeLists.txt
test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu-dpas.mlir
test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu-stages.mlir
test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu.mlir

Closes #160
This PR copies `LinalgToXeGPU` pass from [tpp-mlir project](https://github.com/plaidml/tpp-mlir/blob/main/lib/TPP/GPU/LinalgToXeGPU.cpp), conversion tests, and a few files with utilities that are used by `LinalgToXeGPU.cpp` (unused utilities were removed from these files).
Things to do:

[WIP] Copy LinalgToXeGPU pass from tpp-mlir

---

include/gc-c/Passes.h
include/gc/Transforms/Passes.h
include/gc/Transforms/Passes.td
lib/gc/CAPI/Passes.cpp
lib/gc/Transforms/Pipeline.cpp
python/MainModule.cpp
src/gc-opt/gc-opt.cpp

The all-in-one pass is not debug-friendly, and the real pipeline can provide more information about each pass.
Track: https://github.com/intel/graph-compiler/issues/173
Example:
for the following cmd:
`./bin/gc-opt /home/xurui/gc_v2/test.mlir   --gc-cpu-pipeline  --mlir-print-ir-after-all `
**all-in-one pass**
```
// -----// IR Dump After GCCPUPipeline (gc-cpu-pipeline) //----- //
module {
llvm.func @main_entry(%arg0: !llvm.ptr, %arg1: !llvm.ptr, %arg2: i64, %arg3: i64, %arg4: i64, %arg5: i64, %arg6: i64, %arg7: !llvm.ptr, %arg8: !llvm.ptr, %arg9: i64, %arg10: i64, %arg11: i64, %arg12: i64, %arg13: i64, %arg14: !llvm.ptr, %arg15: !llvm.ptr, %arg16: i64, %arg17: i64, %arg18: i64, %arg19: i64, %arg20: i64) attributes {llvm.emit_c_interface} {
%0 = llvm.mlir.constant(256 : index) : i64
%1 = …
```

replace all-in-one pass with real pipeline

---

src/gc-cpu-runner/gc-cpu-runner.cpp

Fix gc-cpu-runner parser stage error on bf16 workloads
```
loc("<stdin>":83:53): error: #"arith"<"fastmath<contract>"> : 'none' attribute created with unregistered dialect. If this is intended, please call allowUnregisteredDialects() on the MLIRContext, or use -allow-unregistered-dialect with the MLIR opt tool used
could not parse the input IR
```

Fix gc-cpu-runner arith dialect parsing failure

---

python/CMakeLists.txt
python/MainModule.cpp
python/gc_mlir/_mlir_libs/_site_initialize_0.py
test/mlir/test/gc/Dialect/OneDNNGraph/lit.local.cfg
test/mlir/test/gc/python/dialects/lit.local.cfg
test/mlir/test/gc/python/lit.local.cfg
test/mlir/test/lit.site.cfg.py.in

When `GC_ENABLE_DNNL=OFF`,  we still need 
* remove bindings of onednn_graph dialect
* skip test cases using onednn_graph dialect
track: https://github.com/intel/graph-compiler/issues/212

remove bindings and skip tests when GC_ENABLE_DNNL=OFF

---

include/gc/Analysis/TargetDescriptionAnalysis.h
include/gc/Transforms/Passes.td
lib/gc/Analysis/CMakeLists.txt
lib/gc/Analysis/TargetDescriptionAnalysis.cpp
lib/gc/CAPI/CMakeLists.txt
lib/gc/CMakeLists.txt
lib/gc/ExecutionEngine/Driver/CMakeLists.txt
lib/gc/Transforms/CMakeLists.txt
lib/gc/Transforms/IterativeTilingAndFusion.cpp
lib/gc/Transforms/Pipeline.cpp
lib/gc/Transforms/VerifyTargetDescription.cpp
src/gc-opt/CMakeLists.txt
test/mlir/unittests/Analysis/CMakeLists.txt
test/mlir/unittests/Analysis/TargetDescriptionAnalysisTest.cpp
test/mlir/unittests/CMakeLists.txt

Track: https://github.com/intel/graph-compiler/issues/188

Centralize target description query through DLTI and add verifier pass

---

include/gc/Analysis/TargetDescriptionAnalysis.h
lib/gc/Analysis/TargetDescriptionAnalysis.cpp
lib/gc/Transforms/Pipeline.cpp
lib/gc/Transforms/VerifyTargetDescription.cpp

* Avoid too many noisy warnings and only print warnings in the verification phase.
* Correct the pass target operation

only emit target description warning in verify phase and correct the target op

---

lib/gc/Transforms/Pipeline.cpp

Tracking https://github.com/intel/graph-compiler/issues/218
The root issue is the affine op(`affine.apply`) hasn't been lowered to the llvm dialect so that the `unrealized_conversion_cast` cannot be eliminated by the pass `--reconcile-unrealized-casts`

Enable affine op lowering

---

cmake/onednn.cmake

Tracking [#221](https://github.com/intel/graph-compiler/issues/221)

[Build][Bugfix] Fix build failed when GC_ENABLE_DNNL=ON

---

include/gc/Transforms/Passes.td
lib/gc/Transforms/IterativeTilingAndFusion.cpp
lib/gc/Transforms/TilingUsingInterfaceX.cpp
test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir

Fix issue found in llama2-MLP.
A kind reminder: Please DO NOT use rank-altering behavior of `*_slice`. 
```
%extracted_slice_3 = tensor.extract_slice %pack[0, %arg5, 0, 0] [1, 32, 32, 32] [1, 1, 1, 1] : tensor<1x128x32x32xbf16> to tensor<32x32x32xbf16>
%19 = linalgx.batch_reduce_matmul_vnni ins(%extracted_slice_3, %extracted_slice_4 : tensor<32x32x32xbf16>, tensor<32x16x32x2xbf16>) outs(%18 : tensor<32x32xf32>) -> tensor<32x32xf32>
```
Although it is valid and convenient to implicitly reduce rank from `[1, 32, 32, 32]` to `[32, 32, 32]`, fused `packOp` will never yield `[32, 32, 32]`, which will lead to unexpected conflict finally.
Instead, Please explicitly use `tensor.collapse_shape` and `tensor.expand_shape` to alter rank of `*_slice`.

[Transform][Fusion] Support fusion for K-tiling deep matmul

---

lib/gc/Transforms/IterativeTilingAndFusion.cpp
lib/gc/Transforms/TilingUsingInterfaceX.cpp
test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir

Compared with upstream MLIR, although we have enabled multiple consumers fusion, it furthermore need to solve following residual topology: (It seems also found in llama MLP and MHA)
```
op1
/  \
|  op2
|   /
op3
```
where the possible IR may appears like below before fusing `op3`:
```
%1:2 = scf.for() {
%2 = tiled_op1
%3 = tiled_op2
%4 = insert_slice %2
%5 = insert_slice %3
yield %4, %5
}
op3 ins(%1#1, %1#2)
```
Current fuse consumer only accepts single one candidate slice, saying `%4`, However, in fact, `%5` is another slice regarding to operand of untiled `op3`. Thus, is is necessary to find all of the them and make sure that they are pretty matched.
BTW, this is also an interesting topic concerned by community in our upstream [RFC](https://discourse.llvm.org/t/rfc-introduce-new-pass-tra …

[Transform][Fusion] support fusion for residual pattern

---

lib/gc/Transforms/IterativeTilingAndFusion.cpp
test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir

1. Fix Pack/unPack filter logic by `getInnerDimsPos` instead of `getDimAndTileMapping`.
2. When one of multiple consumers failed to fuse, move its operand to the last in use-list in avoid of repeated attempts.
3. Split `linalgOp` and `TensorOp` tiling priority.

[Transform][Fusion] fix pack/unpack filter

---

lib/gc/Transforms/IterativeTilingAndFusion.cpp
test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir

Resolve #239.
This patch will ensure each tilable op would be loaded/stored at least 2D tiles.

[Transform][Fusion] optimize default tileSize to 2D-tile

---

python/CMakeLists.txt
python/config.py.in
python/gc_mlir/graph_compiler.py

fix the issue of https://github.com/intel/graph-compiler/issues/254

Adding the shared lib GcCpuRuntime for python GraphCompiler

---

lib/gc/ExecutionEngine/CPURuntime/MemoryPool.cpp
lib/gc/Transforms/MemRefToCPURuntime.cpp

This PR related to [Issue#257](https://github.com/intel/graph-compiler/issues/257#issuecomment-2295726130).
1. set unknown op as legal
2. remove unuesd clear() func

Bug fix for correctness check

---

scripts/compile.sh

Track https://github.com/intel/graph-compiler/issues/263
The cause is that llvm use the imex version in CPU pipeline and doesn't contain the root fix https://github.com/intel/graph-compiler/pull/247

Correct the llvm version in build script for CPU pipeline

---

scripts/compile.sh

The script fails when using relative paths and symbolic links.

Do not use relative paths in the build script

---

cmake/onednn_lite_config.cmake
lib/gc/ExecutionEngine/CPURuntime/MemoryPool.cpp

There are 2 failures when building with clang:
```
CMake Error at cmake/onednn_lite_config.cmake:208 (message):
Unsupported Clang sanitizer ''
```
```
Cannot resolve symbol 'uint64_t'
```

Fixed clang build

---

docs/benchgc_overview.md

[Doc] Introduce the validation tool, benchgc

---

scripts/compile.sh

There are 2 issues with the current build:
1. Invalid path to imex-version.txt
2. git apply may faild if the patches are applied in an incorrect order
Also, enabled the llvm tests.

Fixed imex build

---

.github/workflows/clang-tidy.yml
scripts/compile.sh

Use gh to download llvm artifact

Switch to gh

---

include/gc/Transforms/Passes.td
lib/gc/Transforms/IterativeTilingAndFusion.cpp
test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir

Since our upstream patch has been merged, revert fusing `tensor.pack` as a consumer.

[Transform][Fusion] revert consumer fusion for `tensor.pack`

---

lib/gc/Transforms/Pipeline.cpp

Fix part of issue https://github.com/intel/graph-compiler/issues/288
`empty_tensor_elimination` could eliminate the copy introduced by `bufferization.materialize_in_destination`. And adjust the pipeline according to the doc(https://mlir.llvm.org/docs/Bufferization/#overview).

Align the bufferization pipeline according to the upstream doc

---

lib/gc/Transforms/TilingUsingInterfaceX.cpp
test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir

Automatically yield fused producer if it has multiple uses. E,g,
```
func.func @yield_fused_producer(%arg0: tensor<16x32x32xf32>) -> (tensor<16x32x32xf32>, tensor<16x32xf32>) {
%cst_0 = arith.constant dense<2.000000e+00> : tensor<16x32x32xf32>
%dest0 = tensor.empty() : tensor<16x32x32xf32>
%0 = linalg.powf ins(%arg0, %cst_0 : tensor<16x32x32xf32>, tensor<16x32x32xf32>) outs(%dest0 : tensor<16x32x32xf32>) -> tensor<16x32x32xf32>
%dest1 = tensor.empty() : tensor<16x32xf32>
%1 = linalg.reduce { arith.addf } ins(%0 : tensor<16x32x32xf32>) outs(%dest1 : tensor<16x32xf32>) dimensions = [2]
return %0, %1 : tensor<16x32x32xf32>, tensor<16x32xf32>
}
```
When fusing `powf` into tiled consumer `reduce`, `%0` should also be yield because it has two users. Otherwise, there would exist repeat `powf` …

[Transform][Fusion] yield fused producer if necessary

---

lib/gc/Transforms/Pipeline.cpp

Track Issue: https://github.com/intel/graph-compiler/issues/301
The tiling and fusion related pass has already generated the outer parallel loop while the `linalgToParallelLoopPass` will create the parallel loop again. And there will be nested omp parallel which hurt the performance a lot.
Before this PR
```
module @fragment_name attributes {"#dlti.sys_spec" = #dlti.target_system_spec<"CPU" : #dlti.target_device_spec<#dlti.dl_entry<"tile_size", 32 : i32>, #dlti.dl_entry<"num_threads", 32 : i32>>>} {
func.func @entry(%arg0: memref<1024x1024xf32>, %arg1: memref<128x1024xf32>, %arg2: memref<128x1024xf32>, %arg3: memref<128x1024xf32>) {
%c1024 = arith.constant 1024 : index
%c128 = arith.constant 128 : index
%c1 = arith.constant 1 : index
%c0 = arith.constant 0 : index
%c64 = arith.constant 64 …
```

fix nested parallel loop introduced by linalg op lowering

---

lib/gc/Transforms/IterativeTilingAndFusion.cpp

[Transform][Fusion] fix `getClosestExtractSliceOfOperand` when `operand` is block argument of function

---

lib/gc/Transforms/IterativeTilingAndFusion.cpp
test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir

Sometimes, the `insert_slice` generated by deep tiled matmul would be eliminated before fusion due to the same size of `SRC` and `DEST`.
This patch can also fix #305 .

[Transform][Fusion] loose `isTiledOpInLoop` check to cover no `insert_slice` case

---

lib/gc/Transforms/Pipeline.cpp

Fix [Issue#306](https://github.com/intel/graph-compiler/issues/306).
MathToLLVMPass is not a func pass.

[Transform] fix legalization on absi

---

lib/gc/Transforms/IterativeTilingAndFusion.cpp
lib/gc/Transforms/TilingUsingInterfaceX.cpp
lib/gc/Transforms/TilingUsingInterfaceX.h
test/mlir/test/gc/Transforms/iterative-tiling-and-fusion.mlir

Track #315.
BTW, the root cause is that upstream function `addInitOperandsToLoopNest` assumes nested loops must be `scf.for` instead of `scf.forall`. It may take more time to fix it upstream.

[Transform][Fusion] fix `whileProducerOutOfLoopBlock` logic

---

test/benchgc/src/benchgc/__main__.py
test/benchgc/src/benchgc/mlir/module.py
test/benchgc/src/benchgc/pattern/mlp.py

when driver is mlir, the `llvm.emit_c_interface` is not added automatically. 
This PR added the `llvm.emit_c_interface` attr after creating the ir module.

fix BenchGC execution issue when driver is mlir

---

.github/actions/setup-mlir-python-bindings/action.yml
.github/workflows/build-gpu-imex.yml
.github/workflows/build.yml
.github/workflows/coverity.yml

This fixes Coverity scans and unifies CI code.

Reuse code, fix Coverity scans

---

scripts/correctness.sh
test/benchgc/src/benchgc/__main__.py
test/benchgc/src/benchgc/linalg/misc.py

benchgc: support transpose op

---

lib/gc/Transforms/CMakeLists.txt
lib/gc/Transforms/IterativeTilingAndFusion.cpp
lib/gc/Transforms/Pipeline.cpp
lib/gc/Transforms/TileUsingInterfaceX.cpp
lib/gc/Transforms/TileUsingInterfaceX.h
lib/gc/Transforms/TilingUtil.hpp

To distinguish two upstream file `tileUsingInterface` and `TilingInterface` and reduce confusion.

[Transform][Fusion] align file name with upstream

---

lib/gc/ExecutionEngine/CPURuntime/Microkernel/BrgemmOnednn.cpp

Tracking [Issue#323](https://github.com/intel/graph-compiler/issues/323)

add thread local cache for brgemm

---

cmake/functions.cmake
include/gc/ExecutionEngine/GPURuntime/GpuOclRuntime.h
lib/gc/ExecutionEngine/GPURuntime/ocl/GpuOclRuntime.cpp
src/gc-cpu-runner/CMakeLists.txt
src/gc-gpu-runner/CMakeLists.txt
src/gc-gpu-runner/GpuRunner.cpp
test/mlir/test/CMakeLists.txt
test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_128x64_transpose.mlir
test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_128x64_transpose_sep.mlir
test/mlir/test/gc/gpu-runner/XeGPU/f16_matmul_64x64.mlir
test/mlir/test/gc/gpu-runner/XeGPU/f16_mlp_32x4096x4096x4096.mlir
test/mlir/test/gc/gpu-runner/XeGPU/f16_mlp_32x4096x4096x4096_transpose.mlir
test/mlir/test/gc/gpu-runner/mlp.mlir
test/mlir/test/lit.cfg.py

Implemented GPU runner

---

include/gc/ExecutionEngine/GPURuntime/GpuOclRuntime.h
lib/gc/ExecutionEngine/GPURuntime/ocl/GpuOclRuntime.cpp

Call clRetainEvent() for each event passed to OclContext and clReleaseEvent() for each created event.
Also, minor refactoring of the events management code.

[GpuOclRuntime] Retain input and release created cl_events

---

cmake/imex.cmake
scripts/compile.sh

-  Added `-s` option for the build dir suffix.
-  Added `-v` option that allows to build LLVM only.
-  Get the IMEX repository url directly from the cmake file.
- Changed the IMEX source directory to `imex-src` - this directory is also used by cmake.

Minor build script enhancements

---

include/gc/Analysis/MatmulConfigAnalysis.h
lib/gc/Analysis/MatmulConfigAnalysis.cpp

Add matmul config validity check to avoid invalid configs.
Resolves issue #375 and #377.

Add config validity check

---

lib/gc/ExecutionEngine/GPURuntime/ocl/GpuOclRuntime.cpp

The queue properties, passed to clCreateCommandQueueWithProperties() are not valid.

[GpuOclRuntime] Fixed createQueue()

---

scripts/compile.sh

A clean build currently fails with:
```
error: pathspec '.' did not match any file(s) known to git
```
This patch fixes the problem which is creating llvm source folder unconditionally before checking for its existence.

Fix compile.sh for a clean build

---

include/gc/Dialect/LLVMIR/XeVMDialect.h
include/gc/Dialect/LLVMIR/XeVMOps.td
lib/gc/Dialect/LLVMIR/IR/XeVMDialect.cpp

I've split the single cache control record into multiple of the same class to add some flexibility for changes to cache control policies and their number. It makes the ops fields a bit more explicit but verification (and other) logic will now be isolated for each cache level.
Depends on #387.

Add XeVM block store/load ops definition

---

lib/gc/Dialect/LLVMIR/IR/XeVMDialect.cpp
test/mlir/test/gc/Dialect/XeVM/xevm-invalid.mlir

This adds the necessary validation for HW parameters of the memory operations and diagnostic tests.
Depends on #389

[GPU] Add 2d load/store ops validation

---

include/gc/Transforms/Passes.td
lib/gc/Transforms/GPU/AllocsToSLM.cpp
lib/gc/Transforms/GPU/CMakeLists.txt
test/mlir/test/gc/Transforms/GPU/allocs-to-slm.mlir

Fixes #393 
The new pass goes through each `memref.alloc()` inside of a `gpu.launch block {}` and sets shared mem-space attribute (int value of 3) to the resulted memref (it ignores all memrefs that already have explicitly specified mem-space).

Add shared mem-space for SLM allocs

---

cmake/functions.cmake
include/gc/CMakeLists.txt
include/gc/Conversion/CMakeLists.txt
include/gc/Conversion/Passes.h
include/gc/Conversion/Passes.td
include/gc/Conversion/XeVMToLLVM/XeVMToLLVM.h
lib/gc/CMakeLists.txt
lib/gc/Conversion/CMakeLists.txt
lib/gc/Conversion/XeVMToLLVM/CMakeLists.txt
lib/gc/Conversion/XeVMToLLVM/XeVMToLLVM.cpp

This adds the lowering pass boilerplate for `convert-xevm-to-llvm`.
Depends on #390.

[GPU] XeVM to LLVM pass structure

---

include/gc/Dialect/LLVMIR/XeVMOps.td
include/gc/Target/LLVM/XeVM/Target.h
lib/gc/CMakeLists.txt
lib/gc/Dialect/LLVMIR/IR/XeVMDialect.cpp
lib/gc/Target/CMakeLists.txt
lib/gc/Target/LLVM/CMakeLists.txt
lib/gc/Target/LLVM/XeVM/Target.cpp

This adds proper definition for the attribute and the target library. The implementation will be added together with the translation library.

[GPU] Add xevm.target definition and validation

---

cmake/functions.cmake
include/gc/Target/LLVMIR/Dialect/XeVM/XeVMToLLVMIRTranslation.h
lib/gc/Target/CMakeLists.txt
lib/gc/Target/LLVMIR/XeVM/CMakeLists.txt
lib/gc/Target/LLVMIR/XeVM/XeVMToLLVMIRTranslation.cpp

This adds the placeholder for xevm to llvm ir translation library.

[GPU] Add an empty xevm translation library.

---

lib/gc/Transforms/GPU/AllocsToSLM.cpp
test/mlir/test/gc/Transforms/GPU/allocs-to-slm.mlir

The proper way to use SLM via `memref.alloc()` appears to be allocating the SLM chunk for all threads in the workgroup at once, then slicing it for each thread. This PR implements this logic.
Example:
```mlir
// Before the pass
func.func @entry() {
gpu.launch blocks(%bx, %by, %bz) in (%sz_bx = %c8, %sz_by = %c8, %sz_bz = %c1)
threads(%tx, %ty, %tz) in (%sz_tx = %c2, %sz_ty = %c4, %sz_tz = %c1) {
%slm = memref.alloc() : memref<16x32xf16>
gpu.terminator
}
return
}
// After the pass
func.func @entry() {
gpu.launch blocks(%bx, %by, %bz) in (%sz_bx = %c8, %sz_by = %c8, %sz_bz = %c1)
threads(%tx, %ty, %tz) in (%sz_tx = %c2, %sz_ty = %c4, %sz_tz = %c1) {
// Scale allocation size by the number of threads in the work-group (16 * 2 = 32; 32 * 4 = 128)
// This 'alloc' is only called once per …
```

[AllocsToSLM] Add thread-specific offsets

---

lib/gc/Transforms/GPU/LinalgToXeGPU.cpp
test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu-dpas-transpose.mlir

It was discovered that `linalg.matmul_transpose_b` is lowered to xegpu incorrectly in the case of large tiles. The issue is caused by a `std::swap` placed inside a nested for-loop, which, instead of swapping `rowOffs` and `colOffs` only once, performs the swap in every iteration, resulting in incorrect offsets.

Fix `linalg.matmul_transpose_b` for big tiles

---

include/gc/Target/LLVM/XeVM/Utils.h
lib/gc/Target/LLVM/XeVM/Target.cpp

This adds a spirv serializer to be invoked upon a gpu module with xevm target translation.

[GPU] Implement create and serialize methods of XeVMTargetAttrImpl.

---

include/gc/Transforms/Utils/ValueUtils.h
lib/gc/Transforms/GPU/LinalgToXeGPU.cpp
lib/gc/Transforms/Utils/ValueUtils.cpp
test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu-squeeze.mlir

This PR allows any-D memrefs to be used in `linalg-to-xegpu` pass as long they can be squeezed to a 2D memref through leading dimensions. Example: 
```mlir
// allowed
!chunk_type = memref<1x1x8x16xf16, strided<[512, 128, 16, 1], offset: ?>>
linalg.mul ins(%0, %1 : !chunk_type, !chunk_type) outs(%2 : !chunk_type)
// NOT allowed
!chunk_type = memref<1x8x1x16xf16, strided<[512, 128, 16, 1], offset: ?>>
linalg.mul ins(%0, %1 : !chunk_type, !chunk_type) outs(%2 : !slm_chunk)
```
The `linalg-to-xegpu` logic considers a linalg operation that can be lowered to xegpu and checks the operand shapes. The old logic refused all `linalgOps` that have non-2D operands. The new logic additionally checks if a non-2D operand can be squeezed to a 2D and allows them if they can. It then squeezes the non-2D …

[LinalgToXeGPU] Support squeezable any-D memrefs

---

include/gc/ExecutionEngine/GPURuntime/GpuOclRuntime.h
lib/gc/ExecutionEngine/GPURuntime/ocl/GpuOclRuntime.cpp
src/gc-gpu-runner/GpuRunner.cpp

This should help with kernel debugging. Also, no need to rely on the driver's env variables we had problems with.

[GpuOclRuntime] Add spirv dump option

---

lib/gc/Transforms/GPU/LinalgToXeGPU.cpp
lib/gc/Transforms/GPU/Pipeline.cpp
test/mlir/test/gc/Transforms/GPU/linalg-to-xegpu-broadcast-fold.mlir
test/mlir/test/gc/gpu-runner/XeGPU/rope_sanity_test.mlir

The PR implements logic that removes `linalg.broadcast` ops that do not perform any actual broadcasting. Example:
```mlir
%inp = memref.alloc() : memref<7x128xf16>
%out = memref.alloc() : memref<1x7x128xf16>
linalg.broadcast ins(%inp) out(%out) // doesn't make any sense; can be removed
```
<b>Why not support all broadcast cases?</b>
A proper lowering for broadcast can be tricky, since xegpu only supports 2D memrefs. Broadcast is always a shape-expanding operation, so there's always at least one operand that is not 2D.

[LinalgToXeGPU] Remove redundant linalg.broadcasts

---

include/gc/Conversion/Passes.h
include/gc/Conversion/XeVMToLLVM/XeVMToLLVM.h
include/gc/Dialect/LLVMIR/XeVMOps.td
lib/gc/Conversion/XeVMToLLVM/XeVMToLLVM.cpp
lib/gc/Dialect/LLVMIR/IR/XeVMDialect.cpp
lib/gc/Target/LLVMIR/XeVM/XeVMToLLVMIRTranslation.cpp
src/gc-opt/CMakeLists.txt
src/gc-opt/gc-opt.cpp
test/mlir/test/gc/Conversion/XeVMToLLVM/blockload2d.mlir
test/mlir/test/gc/Conversion/XeVMToLLVM/blockprefetch2d.mlir
test/mlir/test/gc/Conversion/XeVMToLLVM/blockstore2d.mlir

This PR adds XeVM load/store/prefetch operations and their conversion patterns to llvm. We follow the Triton approach with slight changes (e.g., the cache attribute is handled differently).

[XeVM] Add initial set of operations and conversion tests

---

include/gc/Transforms/Passes.td
lib/gc/Target/LLVM/CMakeLists.txt
lib/gc/Transforms/GPU/CMakeLists.txt
lib/gc/Transforms/GPU/XeVMAttachTarget.cpp
src/gc-opt/gc-opt.cpp
test/mlir/test/gc/Transforms/GPU/module-to-binary-xevm.mlir
test/mlir/test/gc/Transforms/GPU/xevm-attach-target.mlir

This PR adds a pass that attaches an xevm target to a GPU module. This enables generating binaries similar to the upstream via `gpu-module-to-binary`.

[XeVM] Attach target pass
